### ISSUE TITLE
Crash Related to Base Metals

### ISSUE THREAD

**Issue by power-spike** [MinecraftModDevelopmentMods/BaseMetals#226]
Greetings, I do belive this issue is not caused by your mods, however the intergration with othermods has some unhandled exceptions by the looks of it. 

-- CUT & PASTE --

Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at com.mcmoddev.lib.fluids.CustomFluid.getLocalizedName(CustomFluid.java:100)
        at net.minecraftforge.fluids.FluidStack.getLocalizedName(FluidStack.java:125)
        at slimeknights.tconstruct.TinkerIntegration.handleAlloyIMCs(TinkerIntegration.java:225)
        at slimeknights.tconstruct.TinkerIntegration.init(TinkerIntegration.java:165)
        ... 37 more

**Comment by dshadowwolf** [comment]
Known error - fixed in dev, please check existing issues before opening a new one

Next release will have this fixed - release will be by next monday.

**Comment by dshadowwolf** [comment]
#227 when merged will fix this.

**Comment by dshadowwolf** [comment]
Maven -beta3.49 has this fixed
