### ISSUE TITLE
Crash on opening with Moar Tinkers Mod.

### ISSUE THREAD

**Issue by SightedNZ** [MinecraftModDevelopmentMods/BaseMetals#233]
I figure the issue is with Base Metals given that the 1.12 version is in Beta. Here's the report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 11/20/17 7:05 PM
**Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Moar Tinkers (moartinkers)
Caused by: slimeknights.tconstruct.library.TinkerAPIException: [TCon API] Could not register Material "platinum": It was already registered by Base Metals**
	at slimeknights.tconstruct.library.TinkerRegistry.error(TinkerRegistry.java:947)
	at slimeknights.tconstruct.library.TinkerRegistry.addMaterial(TinkerRegistry.java:129)
	at com.bartz24.moartinkers.MoarMaterialIntegration.preInit(MoarMaterialIntegration.java:71)
	at com.bartz24.moartinkers.registry.ModMaterials.ingotMaterial(ModMaterials.java:720)
	at com.bartz24.moartinkers.registry.ModMaterials.preInit(ModMaterials.java:120)
	at com.bartz24.moartinkers.proxy.CommonProxy.preInit(CommonProxy.java:24)
	at com.bartz24.moartinkers.proxy.ClientProxy.preInit(ClientProxy.java:14)
	at com.bartz24.moartinkers.MoarTinkers.preInit(MoarTinkers.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:266)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 666593360 bytes (635 MB) / 1735393280 bytes (1655 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.0.2517 Optifine OptiFine_1.12.2_HD_U_C6 32 mods loaded, 32 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version                  | Source                                            | Signature                                |
	|:----- |:------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft           | 1.12.2                   | minecraft.jar                                     | None                                     |
	| UCH   | mcp                 | 9.42                     | minecraft.jar                                     | None                                     |
	| UCH   | FML                 | 8.0.99.99                | forge-1.12.2-14.23.0.2517.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge               | 14.23.0.2517             | forge-1.12.2-14.23.0.2517.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | actuallyadditions   | 1.12.2-r124              | ActuallyAdditions-1.12.2-r124.jar                 | None                                     |
	| UCH   | aroma1997core       | 1.3.0.2                  | Aroma1997Core-1.12.2-1.3.0.2.jar                  | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCH   | aroma1997sdimension | 1.3.0.0.b37              | Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar | None                                     |
	| UCH   | ic2                 | 2.8.16-ex112             | industrialcraft-2-2.8.16-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCH   | jei                 | 4.8.0.114                | jei_1.12.2-4.8.0.114.jar                          | None                                     |
	| UCH   | mantle              | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                          | None                                     |
	| UCH   | tconstruct          | 1.12-2.7.4.34            | TConstruct-1.12-2.7.4.34.jar                      | None                                     |
	| UCH   | basemetals          | 2.5.0-beta3              | BaseMetals-1.12-2.5.0-beta3.51.jar                | None                                     |
	| UCH   | bookshelf           | 2.2.498                  | Bookshelf-1.12.2-2.2.498.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | chameleon           | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| UCH   | crafttweaker        | 4.0.10                   | CraftTweaker2-1.12-4.0.10.jar                     | None                                     |
	| UCH   | ctgui               | 1.0.0                    | CraftTweaker2-1.12-4.0.10.jar                     | None                                     |
	| UCH   | crafttweakerjei     | 2.0.0                    | CraftTweaker2-1.12-4.0.10.jar                     | None                                     |
	| UCH   | gamestages          | 1.0.71                   | GameStages-1.12.2-1.0.71.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | gravestone          | 1.10.0                   | gravestone-1.10.0.jar                             | None                                     |
	| UCH   | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                          | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | ironbackpacks       | 1.12.2-3.0.1-2           | IronBackpacks-1.12.2-3.0.1-2.jar                  | None                                     |
	| UCH   | ironchest           | 1.12.2-7.0.34.820        | ironchest-1.12.2-7.0.34.820.jar                   | None                                     |
	| UCH   | journeymap          | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                       | None                                     |
	| UCH   | jeresources         | 0.8.5.27                 | JustEnoughResources-1.12.2-0.8.5.27.jar           | None                                     |
	| UCH   | mekanism            | 9.4.1                    | Mekanism-1.12.1-9.4.1.326.jar                     | None                                     |
	| UCH   | mekanismtools       | 9.4.1                    | MekanismTools-1.12.1-9.4.1.326.jar                | None                                     |
	| UCE   | moartinkers         | 0.5.4                    | moartinkers-0.5.4.jar                             | None                                     |
	| UCH   | modernmetals        | 2.5.0-beta3              | ModernMetals-1.12-2.5.0-beta3.63.jar              | None                                     |
	| UCH   | moreoverlays        | 1.13                     | moreoverlays-1.13-mc1.12.1.jar                    | None                                     |
	| UCH   | storagedrawers      | 1.12-5.2.5               | StorageDrawers-1.12.1-5.3.3.jar                   | None                                     |
	| UCH   | theoneprobe         | 1.4.19                   | theoneprobe-1.12-1.4.19.jar                       | None                                     |
	| UCH   | tinkerstages        | 1.0.13                   | TinkerStages-1.12.2-1.0.13.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |

	Loaded coremods (and transformers): 
CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 1080 Ti/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_C6
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.6.0 NVIDIA 388.13
	OpenGlRenderer: GeForce GTX 1080 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by dshadowwolf** [comment]
BaseMetals and Moar Tinkers are both trying to register platinum. This crash is technically in the Moar Tinkers side, but the solution is to turn off Platinum in one of them.

**Comment by SightedNZ** [comment]
Thanks for your feedback. 
I've tried disabling Platinum in the assetsassets\basemetals\orespawn\basemetals.json file but I'm getting the same error. 
Is there another file I need to edit to stop Platinum from registering?

**Comment by dshadowwolf** [comment]
Try config/BaseMetals.cfg:
    B:EnablePlatinum=true
is the default, change that to:
    B:EnablePlatinum=false

and Moar Tinkers or another mod can provide platinum - otherwise... unless you turn off Tinkers' integration in BaseMetals completely ( B:tinkers_construct_integration=false  in BaseMetals.cfg) there is no option for stopping it from registering its materials with Tinkers'

**Comment by dshadowwolf** [comment]
in fact... the file you've mentioned is the defaults for BaseMetals OreSpawn integration and just tells OreSpawn where and how to spawn patches of Platinum Ore and has nothing to do with Base Metals providing Platinum to the world.

**Comment by SightedNZ** [comment]
dshadowwolf, you're awesome!

I had to edit the Basemetals.cfg file and disable all of the ores that were enabled in the moartinkers mod. Basically, I've customized a modpack based on Age of Engineering that will work in 1.12 and you've just helped me to get it going.

fyi, i've never paid much attention to that config folder before so you've taught me something :)

Kudos!
