### ISSUE TITLE
[1.12.2] Crash while loading

### ISSUE THREAD

**Issue by KawaiiRuby** [MinecraftModDevelopmentMods/BaseMetals#272]
Minecraft crashes while Forge is loading the mods, removing BaseMetals seems to fix the issue, I really want to play with it though! ;-;
I tried using daily beta builds, for Additional Loot Tables and OreSpawner as well, I tried a new Forge version too, but nothing seemed to fix it so far :c
Thanks for the help in advance!

```
at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:289)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:275)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:108)
	at com.mcmoddev.modernmetals.init.Blocks.registerBlocks(Blocks.java:80)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1226_Blocks_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


```

**Comment by drakray** [comment]
can you post the complete crash using www.pastebin.com please?

**Comment by KawaiiRuby** [comment]
Nevermind, it works now, sorry for posting that!
Apparently, my NotEnoughIDs mod was broken, and while Minecraft recognised it, it still didn't work, so because the vanilla ID limit was exceeded the game crashed, but the crash report didn't reflect on that problem in any way in my understanding, and removing BaseMetals fixed it because I assume I was juust a bit above the limit, but.. it works now.. ^^

**Comment by jriwanek** [comment]
For future reference, you're able to disable parts of BaseMetals you dont want individually, see the config file.
