### ISSUE TITLE
[COL][Maven] VillagerTrades

### ISSUE THREAD

**Issue by drakray** [MinecraftModDevelopmentMods/BaseMetals#302]
```
Caused by: java.lang.NullPointerException
	at com.mcmoddev.lib.material.MMDMaterial.getItemStack(MMDMaterial.java:604)
	at com.mcmoddev.lib.material.MMDMaterial.getItemStack(MMDMaterial.java:591)
	at com.mcmoddev.lib.init.VillagerTrades.getTrades(VillagerTrades.java:59)
	at com.mcmoddev.lib.init.VillagerTrades.insertTrades(VillagerTrades.java:151)
	at com.mcmoddev.lib.init.VillagerTrades.lambda$makeTrades$12(VillagerTrades.java:132)
```

https://pastebin.com/4g9G9y88

using
```
| UCH   | alt           | 2.0.3        | 1-0-MMD-AdditionalLootTables-1.12-2.0.3.37.jar
| UCH   | orespawn      | 3.2.2        | 1-0-MMD-OreSpawn-1.12-3.2.2.114.jar
| UCE   | basemetals    | 2.5.0-beta4  | 1-2-MMD-BaseMetals-1.12-2.5.0-beta4.197.jar
| UCE   | baseminerals  | 2.5.0-beta4  | 1-1-MMD-BaseMinerals-1.12-2.5.0-beta4.38.jar
| UCE   | modernmetals  | 2.5.0-beta4  | 1-3-MMD-ModernMetals-1.12-2.5.0-beta4.112.jar
| UCH   | nethermetals  | 1.2.0-beta2  | 1-4-MMD-NetherMetals-1.12-1.2.0-beta2.45.jar
| UCH   | endmetals     | 1.2.0-beta2  | 1-5-MMD-EndMetals-1.12-1.2.0-beta2.35.jar
| UCH   | mineralogy    | 3.4.0        | 1-7-MMD-Mineralogy-1.12-3.4.0.16.jar
```

**Comment by jriwanek** [comment]
Known issue, for now use the following versions:
BMe build 193
MMe build 109
NMe build 43
EMe build 33
BMi build 33

**Comment by jriwanek** [comment]
fixed
