### ISSUE TITLE
MMD Crashing with itself

### ISSUE THREAD

**Issue by bookerthegeek** [MinecraftModDevelopmentMods/BaseMetals#414]
# Heyo Again
So off the bat, version information:

- Base Metals 2.5.0-beta 6.308
- Base Minerals 2.5.0-beta 6.57
- Ore Spawn 3.3.0.160
- Forge 14.23.5.2807
## Interesting Things...
So I am having an issue with Ore Spawn & Base Metals & Base Minerals ([link to the crash report](https://gist.github.com/bookerthegeek/6b02188a063a324c57dc5ab8104bff59)) Giving me a crash while loading up. This issue is present with or without sponge. Issue is present with older versions of BaseMinerals.
## Crash report Exerpt
``` 
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Base Metals (basemetals)
Caused by: java.lang.NoClassDefFoundError: com/mcmoddev/lib/material/MMDMaterial$MaterialType
	at com.mcmoddev.baseminerals.init.Materials.getType(Materials.java:48)
	at com.mcmoddev.baseminerals.init.Materials.lambda$init$0(Materials.java:34)
	at com.mcmoddev.baseminerals.init.Materials$$Lambda$118/27469226.accept(Unknown Source)
```

**Comment by dshadowwolf** [comment]
check the [MMD Maven](https://maven.mcmoddev.com) soon - this was something I'd overlooked and is just part of a minor re-org and cleanup that I'd forgotten to propogate.
