### ISSUE TITLE
No Such Method Error

### ISSUE THREAD

**Issue by 09jlardinois** [MinecraftModDevelopmentMods/BaseMetals#431]
Eclipse is showing that the net.minecraft.util.ResourceLocation.getPath() method doesn't exist.

It's pointing to (OreDictionaryCrusherRecipe.java:40) where there's one of those obfuscated mappings. Maybe mappings got updated? I don't know how any of this works. I've been programming for 18 years, but I've been programming in Java and Forge for like... 2 days. I'm a noob, sorry.

Running Forge 1.12.2 - 14.23.5.2768, Base Metals 2.5.0, beta 7.311, deobf added to gradle and build path, javadoc and sources too and linked. 

Java is so much more abstract than C and C++ and C# :( I'm not used to this. Sorry if this is a stupid report.

`Time: 4/10/19 7:17 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Base Metals (basemetals)
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.ResourceLocation.getPath()Ljava/lang/String;
	at com.mcmoddev.lib.registry.recipe.OreDictionaryCrusherRecipe.<init>(OreDictionaryCrusherRecipe.java:40)
	at com.mcmoddev.lib.registry.CrusherRecipeRegistry.addNewCrusherRecipe(CrusherRecipeRegistry.java:59)
	at com.mcmoddev.lib.init.Recipes.initPureVanillaCrusherRecipes(Recipes.java:83)
	at com.mcmoddev.lib.init.Recipes.init(Recipes.java:57)
	at com.mcmoddev.basemetals.proxy.CommonProxy.preInit(CommonProxy.java:85)
	at com.mcmoddev.basemetals.proxy.ClientProxy.preInit(ClientProxy.java:40)
	at com.mcmoddev.basemetals.BaseMetals.preInit(BaseMetals.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:626)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.init(Minecraft.java:513)
	at net.minecraft.client.Minecraft.run(Minecraft.java:421)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:25)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_202, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4026455560 bytes (3839 MB) / 4225236992 bytes (4029 MB) up to 4225236992 bytes (4029 MB)
	JVM Flags: 3 total; -Xincgc -Xmx4096M -Xms4096M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID         | Version      | Source                                    | Signature |
	|:----- |:---------- |:------------ |:----------------------------------------- |:--------- |
	| UCH   | minecraft  | 1.12.2       | minecraft.jar                             | None      |
	| UCH   | mcp        | 9.42         | minecraft.jar                             | None      |
	| UCH   | FML        | 8.0.99.99    | forgeSrc-1.12.2-14.23.5.2768.jar          | None      |
	| UCH   | forge      | 14.23.5.2768 | forgeSrc-1.12.2-14.23.5.2768.jar          | None      |
	| UCEE  | basemetals | 2.5.0-beta7  | BaseMetals-1.12-2.5.0-beta7.311-deobf.jar | None      |
	| UC    | forgebp    | 1.0.0        | bin                                       | None      |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 419.67' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
[19:17:30] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:629]: #@!@# Game crashed! Crash report saved to: #@!@# X:\wrkspace\dev\minecraft\1.12.2\forge-1.12.2-14.23.5.2768-mdk\run\.\crash-reports\crash-2019-04-10_19.17.30-client.txt
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
`

**Comment by KiriCattus** [comment]
Random shot in the dark but are you by chance not using MCP mappings build/version stable_39 ?

**Comment by dshadowwolf** [comment]
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.ResourceLocation.getPath()Ljava/lang/String;

Hrm... 2768 might be a bit old - there was a change in mappings that changed net.minecraft.util.ResourceLocation.getResourceDomain() to getNamespace() and net.minecraft.util.ResourceLocation.getResourcePath() to getPath()

But, anyway... unless you're actually developing BaseMetals, there is no reason to use the deobf

**Comment by 09jlardinois** [comment]
I'm only using the deobf so I can use BaseMetals ores in some recipes. I'm just learning MC modding, so nothing I'm releasing, but my long term goal is to create mods built around the cool ore system that BaseMetals adds. 

I'm not sure about the mappings, I don't really know how to mess with that, but I'll go find out.

**Comment by 09jlardinois** [comment]
Okay, so I put the correct MCP version in my build.gradle and re-rain setupDecompWorkspace (I'm assuming that's how it's done), and the error persists. 

Might I need to re-setup the whole Forge workspace fresh with the correct mappings? Or does the gradlew command update them okay?

`[20:58:03] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:58:03] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.CoremodTweaker
[20:58:03] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[20:58:03] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2768 for Minecraft 1.12.2 loading
[20:58:03] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_202, running on Windows 10:amd64:10.0, installed at X:\wrkspace\dev\java\JDK1.8.0u202\jre
[20:58:03] [main/ERROR] [FML]: Apache Maven library folder was not in the format expected. Using default libraries directory.
[20:58:03] [main/ERROR] [FML]: Full: C:\Users\john\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-artifact\3.5.3\7dc72b6d6d8a6dced3d294ed54c2cc3515ade9f4\maven-artifact-3.5.3.jar
[20:58:03] [main/ERROR] [FML]: Trimmed: c:/users/john/.gradle/caches/modules-2/files-2.1/org.apache.maven/maven-artifact/3.5.3/
[20:58:03] [main/INFO] [FML]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[20:58:03] [main/INFO] [FML]: Detected deobfuscated environment, loading log configs for colored console logs.
2019-04-10 20:58:04,227 main WARN Disabling terminal, you're running in an unsupported environment.
[20:58:04] [main/INFO] [FML]: Ignoring missing certificate for coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin), we are in deobf and it's a forge core plugin
[20:58:04] [main/INFO] [FML]: Ignoring missing certificate for coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin), we are in deobf and it's a forge core plugin
[20:58:04] [main/INFO] [FML]: Searching X:\wrkspace\dev\minecraft\1.12.2\forge-1.12.2-14.23.5.2768-mdk\run\.\mods for mods
[20:58:04] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.CoremodTweaker
[20:58:04] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.fml.relauncher.FMLCorePlugin
[20:58:04] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.classloading.FMLForgePlugin
[20:58:04] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:58:04] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[20:58:04] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[20:58:04] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:58:04] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:58:04] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:58:05] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[20:58:05] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:58:05] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[20:58:05] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[20:58:05] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[20:58:05] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[20:58:05] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[20:58:05] [main/INFO] [minecraft/Minecraft]: Setting user: john
[20:58:07] [main/WARN] [minecraft/GameSettings]: Skipping bad option: lastServer:
[20:58:07] [main/INFO] [minecraft/Minecraft]: LWJGL Version: 2.9.4
[20:58:08] [main/INFO] [FML]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_202, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4055977680 bytes (3868 MB) / 4225236992 bytes (4029 MB) up to 4225236992 bytes (4029 MB)
	JVM Flags: 3 total; -Xincgc -Xmx4096M -Xms4096M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 419.67' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
[20:58:08] [main/INFO] [FML]: MinecraftForge v14.23.5.2768 Initialized
[20:58:08] [main/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[20:58:09] [main/INFO] [FML]: Replaced 1036 ore ingredients
[20:58:09] [main/INFO] [FML]: Searching X:\wrkspace\dev\minecraft\1.12.2\forge-1.12.2-14.23.5.2768-mdk\run\.\mods for mods
[20:58:10] [main/INFO] [FML]: Forge Mod Loader has identified 6 mods to load
[20:58:10] [main/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, forgebp, basemetals] at CLIENT
[20:58:10] [main/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, forgebp, basemetals] at SERVER
[20:58:11] [Thread-3/INFO] [FML]: Using sync timing. 200 frames of Display.update took 94449300 nanos
[20:58:11] [main/ERROR] [FML]: The mod basemetals is expecting signature d476d1b22b218a10d845928d1665d45fce301b27 for source BaseMetals-1.12-2.5.0-beta7.311-deobf.jar, however there is no signature matching that description
[20:58:11] [main/FATAL] [basemetals]: versions: thermalexpansion@(,5.3.12.17] - thermalexpansion!!(,5.3.12.17] - {thermalexpansion=com.mcmoddev.lib.integration.IntegrationManager$1@73605fde}
[20:58:11] [main/WARN] [basemetals]: Invalid fingerprint detected!
[20:58:11] [main/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Forge Boilerplate, FMLFileResourcePack:Base Metals
[20:58:11] [main/INFO] [FML]: Processing ObjectHolder annotations
[20:58:11] [main/INFO] [FML]: Found 1168 ObjectHolder annotations
[20:58:11] [main/INFO] [FML]: Identifying ItemStackHolder annotations
[20:58:11] [main/INFO] [FML]: Found 0 ItemStackHolder annotations
[20:58:11] [main/INFO] [FML]: Configured a dormant chunk cache size of 0
[20:58:11] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[20:58:11] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Found status: UP_TO_DATE Target: null
[20:58:11] [Forge Version Check/INFO] [forge.VersionCheck]: [basemetals] Starting version check at https://raw.githubusercontent.com/MinecraftModDevelopmentMods/BaseMetals/master/update.json
[20:58:12] [main/INFO] [basemetals]: java.lang.Thread.getStackTrace(Thread.java:1559): Expanding array variable ItemAxe.ATTACK_DAMAGES to size 256
[20:58:12] [main/INFO] [basemetals]: java.lang.Thread.getStackTrace(Thread.java:1559): Expanding array variable ItemAxe.ATTACK_SPEEDS to size 256
[20:58:12] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:629]: ---- Minecraft Crash Report ----`

and

`Time: 4/10/19 8:58 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Base Metals (basemetals)
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.ResourceLocation.getPath()Ljava/lang/String;
	at com.mcmoddev.lib.registry.recipe.OreDictionaryCrusherRecipe.<init>(OreDictionaryCrusherRecipe.java:40)
	at com.mcmoddev.lib.registry.CrusherRecipeRegistry.addNewCrusherRecipe(CrusherRecipeRegistry.java:59)
	at com.mcmoddev.lib.init.Recipes.initPureVanillaCrusherRecipes(Recipes.java:83)
	at com.mcmoddev.lib.init.Recipes.init(Recipes.java:57)
	at com.mcmoddev.basemetals.proxy.CommonProxy.preInit(CommonProxy.java:85)
	at com.mcmoddev.basemetals.proxy.ClientProxy.preInit(ClientProxy.java:40)
	at com.mcmoddev.basemetals.BaseMetals.preInit(BaseMetals.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:626)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.init(Minecraft.java:513)
	at net.minecraft.client.Minecraft.run(Minecraft.java:421)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:25)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_202, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4058974976 bytes (3870 MB) / 4225236992 bytes (4029 MB) up to 4225236992 bytes (4029 MB)
	JVM Flags: 3 total; -Xincgc -Xmx4096M -Xms4096M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID         | Version      | Source                                    | Signature |
	|:----- |:---------- |:------------ |:----------------------------------------- |:--------- |
	| UCH   | minecraft  | 1.12.2       | minecraft.jar                             | None      |
	| UCH   | mcp        | 9.42         | minecraft.jar                             | None      |
	| UCH   | FML        | 8.0.99.99    | forgeSrc-1.12.2-14.23.5.2768.jar          | None      |
	| UCH   | forge      | 14.23.5.2768 | forgeSrc-1.12.2-14.23.5.2768.jar          | None      |
	| UCH   | forgebp    | 1.0.0        | bin                                       | None      |
	| UCEE  | basemetals | 2.5.0-beta7  | BaseMetals-1.12-2.5.0-beta7.311-deobf.jar | None      |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 419.67' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
[20:58:12] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:629]: #@!@# Game crashed! Crash report saved to: #@!@# X:\wrkspace\dev\minecraft\1.12.2\forge-1.12.2-14.23.5.2768-mdk\run\.\crash-reports\crash-2019-04-10_20.58.12-client.txt
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
`

**Comment by 09jlardinois** [comment]
Got it running. Using stable_39 mappings in build.gradle and Forge 1.12.2 Latest instead of Recommended fixes it. Sorry for being masternoob. 

And thank you guys for being patient and giving me hints rather than answers. Hunting down solutions with those hints taught me a lot about how this process all works as a side effect. 

Solved, and closed.
Time for bed.

**Comment by KiriCattus** [comment]
Should you need any more help there's plenty of willing people over in [MMD's Discord](https://discord.mcmoddev.com) id you have discord, a bunch of guides for us newer modders too :)

**Comment by 09jlardinois** [comment]
Thank you! I really appreciate that :)
