### ISSUE TITLE
CRASH - BASE METALS WITH CONARM

### ISSUE THREAD

**Issue by GoblinCwl** [MinecraftModDevelopmentMods/BaseMetals#466]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (S-Forgelin-1.8.4.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 2/3/20 2:22 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MMDLib (mmdlib)
Caused by: slimeknights.tconstruct.library.TinkerAPIException: [TCon API] Could not add Stat of type "core": Default Material does not have default stats for said type. Please add default-values to the default material "unknown" first.
	at slimeknights.tconstruct.library.TinkerRegistry.error(TinkerRegistry.java:986)
	at slimeknights.tconstruct.library.TinkerRegistry.addMaterialStats(TinkerRegistry.java:242)
	at slimeknights.tconstruct.library.TinkerRegistry.addMaterialStats(TinkerRegistry.java:210)
	at com.mcmoddev.basemetals.integration.plugins.BMeConstructsArmory.lambda$materialRegistration$1(BMeConstructsArmory.java:47)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Unknown Source)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at com.mcmoddev.basemetals.integration.plugins.BMeConstructsArmory.materialRegistration(BMeConstructsArmory.java:46)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_138_BMeConstructsArmory_materialRegistration_MaterialRegistrationEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at com.mcmoddev.lib.integration.plugins.TinkersConstruct.preInit(TinkersConstruct.java:116)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_127_TinkersConstruct_preInit_IntegrationPreInitEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at com.mcmoddev.lib.integration.IntegrationManager.preInitPhase(IntegrationManager.java:194)
	at com.mcmoddev.lib.proxy.CommonProxy.preInit(CommonProxy.java:62)
	at com.mcmoddev.lib.proxy.ClientProxy.preInit(ClientProxy.java:31)
	at com.mcmoddev.lib.MMDLib.preInit(MMDLib.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 81923456 bytes (78 MB) / 419430400 bytes (400 MB) up to 10485760000 bytes (10000 MB)
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx9999m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                 | Version                  | Source                                    | Signature                                |
	|:----- |:------------------ |:------------------------ |:----------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft          | 1.12.2                   | minecraft.jar                             | None                                     |
	| LCH   | mcp                | 9.42                     | minecraft.jar                             | None                                     |
	| LCH   | FML                | 8.0.99.99                | forge-1.12.2-14.23.5.2847.jar             | None                                     |
	| LCH   | forge              | 14.23.5.2847             | forge-1.12.2-14.23.5.2847.jar             | None                                     |
	| LCH   | mantle             | 1.12-1.3.3.55            | S-Mantle-1.3.3.55.jar                     | None                                     |
	| LCH   | tconstruct         | 1.12.2-2.13.0.171        | S-TIC-Tinkers'Construct-2.13.0.171.jar    | None                                     |
	| LCE   | mmdlib             | 1.0.0-rc2                | S-MMDLib-1.12-1.0.0-rc2.36.jar            | None                                     |
	| LC    | conarm             | 1.2.5.3                  | S-TIC-Construct'sArmory-1.2.5.3.jar       | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LC    | basemetals         | 2.5.0-rc2                | BaseMetals-1.12-2.5.0-rc2.332.jar         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | modernmetals       | 2.5.0-rc2                | ModernMetals-1.12-2.5.0-rc2.152.jar       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | forgelin           | 1.8.4                    | S-Forgelin-1.8.4.jar                      | None                                     |
	| LC    | redstoneflux       | 2.1.0                    | S-RedstoneFlux-1.12-2.1.0.6-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | tinker_io          | rw2.7.1                  | S-TIC-tinker_io-1.12.2-rw2.7.1.jar        | None                                     |
	| LC    | tinkersaddons      | 1.0.7                    | S-TIC-Tinkers'+Addons-1.12.1-1.0.7.jar    | None                                     |
	| LC    | tcomplement        | 1.12.2-0.4.2             | S-TIC-TinkersComplement-1.12.2-0.4.2.jar  | None                                     |
	| LC    | tinkertoolleveling | 1.12.2-1.1.0.DEV.b23e769 | S-TIC-tinkertoolleveling-1.1.0.jar        | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (S-Forgelin-1.8.4.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 419.71' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleMelter (Enabled/Not Forced)
		- ModuleArmor (Enabled/Not Forced)
		- ModuleSteelworks (Enabled/Not Forced)
		- ToolLevelingPlugin (Enabled/Not Forced)
		- Oredict (Enabled/Forced)

```

**Comment by dshadowwolf** [comment]
@YaibaToKen I thought we had this one fixed in the current release ?

**Comment by GoblinCwl** [comment]
> @YaibaToKen I thought we had this one fixed in the current release ?

fix it   ,PLS !!!!!!

**Comment by jriwanek** [comment]
Don't be rude.

**Comment by GoblinCwl** [comment]
> 

Sorry, my English is very poor and I don't understand the disrespectful behavior that language may carry. I happened to see this issue and I apologize for my previous statement.
